name: Build Docker Image (JVM)
on:
  workflow_call:
    inputs:
      docker_file:
        required: false
        type: string
        default: Dockerfile
      docker_context:
        required: false
        type: string
        default: "."
      image_file:
        required: false
        type: string
        default: image.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: build image
      run: docker build -t ghcr.io/${{ github.repository }}:${GITHUB_SHA} -f ${{ inputs.docker_file }} ${{ inputs.docker_context }} --label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}" --label "org.opencontainers.image.revision=${GITHUB_SHA}"
    - name: Login to GitHub Container Registry
      if: github.ref == inputs.target_ref
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker push
      if: github.ref == inputs.target_ref
      run: |
        docker push ghcr.io/${{ github.repository }}:${GITHUB_SHA}
        docker tag ghcr.io/${{ github.repository }}:${GITHUB_SHA} ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:latest
    - name: Generate digest
      if: github.ref == inputs.target_ref
      run: |
        cat <<EOF > ${{ inputs.image_file }}
        image: $(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}:${GITHUB_SHA})
        git_revision: ${GITHUB_SHA}
        EOF
    - name: Upload artifact
      if: github.ref == inputs.target_ref
      uses: actions/upload-artifact@v2
      with:
        name: image
        path: ${{ inputs.image_file }}