name: Build Docker Image (JVM)
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '21'
      distribution:
        required: false
        type: string
        default: 'graalvm'
      target_ref:
        required: false
        type: string
        default: 'refs/heads/main'
      image_name:
        required: false
        type: string
        default: image
      image_file:
        required: false
        type: string
        default: image.yaml
      download_target:
        required: false
        type: boolean
        default: true
      use_tanzu_buildpack:
        required: false
        type: boolean
        default: false
      maven_server_id:
        required: false
        type: string
        default: ""
      maven_username:
        required: false
        type: string
        default: ""
      maven_password:
        required: false
        type: string
        default: ""
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: ${{ inputs.version }}
        distribution: ${{ inputs.distribution }}
        cache: 'maven'
    - name: Prepare Maven settings.xml
      if: inputs.maven_server_id != '' && inputs.maven_username != '' && inputs.maven_password != ''
      uses: categolj/workflows/.github/actions/prepare-settings-xml@main
      with:
        server_id: ${{ inputs.maven_server_id }}
        username: ${{ inputs.maven_username }}
        password: ${{ inputs.maven_password }}
    - name: Download build artifacts
      if: inputs.download_target
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: target
    - name: Set version
      uses: making/workflows/.github/actions/set-version-with-sha@main
    - name: build image (Paketo Buildpack)
      if: ${{ !inputs.use_tanzu_buildpack }}
      run: ./mvnw -V --no-transfer-progress spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA}
    - name: build image (Tanzu Buildpack)
      if: inputs.use_tanzu_buildpack
      run: ./mvnw -V --no-transfer-progress spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA} -Dspring-boot.build-image.builder=tanzu-build-public.packages.broadcom.com/builders/builder-jammy-base:0.1.37
    - name: Login to GitHub Container Registry
      if: github.ref == inputs.target_ref
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker push
      if: github.ref == inputs.target_ref
      run: |
        docker push ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA}
        docker tag ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA} ghcr.io/${{ github.repository }}:jvm
        docker push ghcr.io/${{ github.repository }}:jvm
    - name: Generate digest
      if: github.ref == inputs.target_ref
      run: |
        cat <<EOF > ${{ inputs.image_file }}
        image: $(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA})
        git_revision: ${GITHUB_SHA}
        EOF
    - name: Upload artifact
      if: github.ref == inputs.target_ref
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.image_name }}
        path: ${{ inputs.image_file }}
