name: Build Docker Image (JVM)
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '21'
      distribution:
        required: false
        type: string
        default: 'graalvm'
      target_ref:
        required: false
        type: string
        default: 'refs/heads/main'
      image_file:
        required: false
        type: string
        default: image.yaml
      download_target:
        required: false
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: ${{ inputs.version }}
        distribution: ${{ inputs.distribution }}
        cache: 'maven'
    - name: Download build artifacts
      if: inputs.download_target
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: target
    - name: Set version
      uses: making/workflows/.github/actions/set-version-with-sha@main
    - name: build image
      run: ./mvnw -V --no-transfer-progress spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA}
    - name: Login to GitHub Container Registry
      if: github.ref == inputs.target_ref
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker push
      if: github.ref == inputs.target_ref
      run: |
        docker push ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA}
        docker tag ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA} ghcr.io/${{ github.repository }}:jvm
        docker push ghcr.io/${{ github.repository }}:jvm
    - name: Generate digest
      if: github.ref == inputs.target_ref
      run: |
        cat <<EOF > ${{ inputs.image_file }}
        image: $(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository }}:jvm_${GITHUB_SHA})
        git_revision: ${GITHUB_SHA}
        EOF
    - name: Upload artifact
      if: github.ref == inputs.target_ref
      uses: actions/upload-artifact@v4
      with:
        name: image
        path: ${{ inputs.image_file }}
