name: Maven Unit Test
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '21'
      distribution:
        required: false
        type: string
        default: 'graalvm'
      jar:
        required: false
        type: boolean
        default: false
      e2e_test:
        required: false
        type: boolean
        default: false
      test_url_1:
        required: false
        type: string
        default: ""
      test_url_2:
        required: false
        type: string
        default: ""
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: ${{ inputs.version }}
        distribution: ${{ inputs.distribution }}
        cache: 'maven'
    - name: mvn test
      env:
        _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
      run: ./mvnw -V --no-transfer-progress test
    - name: Build Jar
      if: inputs.jar
      run: ./mvnw -V --no-transfer-progress package -DskipTests
    - name: Prepare wait.sh
      if: inputs.jar && inputs.e2e_test
      run: wget -q https://github.com/making/workflows/raw/main/wait.sh
    - name: E2E Test
      if: inputs.jar && inputs.e2e_test
      env:
        TEST_URL_1: ${{ inputs.test_url_1 }}
        TEST_URL_2: ${{ inputs.test_url_2 }}
      run: |
        java -jar target/*.jar & ./wait.sh
        if [ -n "${TEST_URL_1}" ]; then
          curl --fail --show-error --silent "${TEST_URL_1}"
        fi
        if [ -n "${TEST_URL_2}" ]; then
          curl --fail --show-error --silent "${TEST_URL_2}"
        fi
        pkill -KILL java
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: target