name: Push Multi Arch Image
on:
  workflow_call:
    inputs:
      prefix:
        required: true
        type: string
      pom_dir:
        required: false
        type: string
        default: '.'
      target_ref:
        required: false
        type: string
        default: 'refs/heads/main'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      if: github.ref == inputs.target_ref
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker manifest push
      if: github.ref == inputs.target_ref
      run: |
        IMAGE_BASE=$(echo "ghcr.io/${{ github.repository }}/${{ inputs.pom_dir }}:${{ inputs.prefix }}" | sed 's|/\.||')
        docker manifest create ${IMAGE_BASE}_${GITHUB_SHA} --amend ${IMAGE_BASE}_amd64_${GITHUB_SHA} --amend ${IMAGE_BASE}_aarch64_${GITHUB_SHA}
        docker manifest push ${IMAGE_BASE}_${GITHUB_SHA}
        docker manifest create ${IMAGE_BASE} --amend ${IMAGE_BASE}_amd64_${GITHUB_SHA} --amend ${IMAGE_BASE}_aarch64_${GITHUB_SHA}
        docker manifest push ${IMAGE_BASE}