name: Unit Test
on:
  workflow_call:
    inputs:
      pom_dir:
        required: false
        type: string
        default: '.'
      e2e_test:
        required: false
        type: boolean
        default: false
      test_url_1:
        required: false
        type: string
        default: ""
      test_url_2:
        required: false
        type: string
        default: ""
      maven_server_id:
        required: false
        type: string
        default: ""
    secrets:
      maven_username:
        required: false
      maven_password:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get tags
      run: |
        git tag -d $(git tag)
        git fetch --tags origin
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: graalvm
        cache: 'maven'
    - name: Prepare Maven settings.xml
      if: inputs.maven_server_id != '' && secrets.maven_username != '' && secrets.maven_password != ''
      uses: categolj/workflows/.github/actions/prepare-settings-xml@main
      with:
        server_id: ${{ inputs.maven_server_id }}
        username: ${{ secrets.maven_username }}
        password: ${{ secrets.maven_password }}
    - name: unit test
      run: ./mvnw -V -f ${{ inputs.pom_dir }} clean test --no-transfer-progress
      env:
        AWS_REGION: ap-northeast-1
    - name: Build Jar
      if: inputs.e2e_test
      run: ./mvnw -V -f ${{ inputs.pom_dir }} package -DskipTests --no-transfer-progress
    - name: Prepare wait.sh
      if: inputs.e2e_test
      run: |
        wget -q https://github.com/making/workflows/raw/main/wait.sh
        chmod +x wait.sh
    - name: E2E Test
      if: inputs.e2e_test
      env:
        TEST_URL_1: ${{ inputs.test_url_1 }}
        TEST_URL_2: ${{ inputs.test_url_2 }}
      run: |
        java -jar ${{ inputs.pom_dir }}/target/*.jar --server.port=8080 & ./wait.sh
        if [ -n "${TEST_URL_1}" ]; then
          curl --fail --show-error --silent "${TEST_URL_1}"
        fi
        if [ -n "${TEST_URL_2}" ]; then
          curl --fail --show-error --silent "${TEST_URL_2}"
        fi
        pkill -KILL java
